name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin
      - name: Docker pull and push
        run: |
          orgin=pgvector/pgvector:0.8.0-pg15
          mirror=ghcr.io/xia-fei/pgvector:0.8.0-pg15
          docker pull $orgin
          docker tag  $orgin $mirror      
          docker push $mirror
